### ISSUE TITLE
Submit filter rejects the default -C argument

### ISSUE THREAD

**Issue by ehiggs** [hpcugent/vsc-jobs#68]
`qsub -C '#PBS' script.sh` is rejected as follows:

```
$ qsub -C '#PBS' lang.sh
/usr/lib/python2.6/site-packages/vsc/jobs/__init__.py:32: UserWarning: Module vsc was already imported from None, but /usr/lib/python2.6/site-packages is being added to sys.path
  import pkg_resources
Traceback (most recent call last):
  File "/usr/bin/submitfilter", line 150, in <module>
    main()
  File "/usr/bin/submitfilter", line 126, in main
    sf = SubmitFilter(arguments, sys.stdin.readline)
  File "/usr/lib/python2.6/site-packages/vsc/jobs/pbs/submitfilter.py", line 95, in __init__
    self.set_pbs_header_regexp()
  File "/usr/lib/python2.6/site-packages/vsc/jobs/pbs/submitfilter.py", line 104, in set_pbs_header_regexp
    self.regexp = re.compile(r"^" + dprefix + r"\s+([^#]*)\s*(?:#|$)")
TypeError: cannot concatenate 'str' and 'NoneType' objects
qsub: submit filter returned an error code, aborting job submission.
```

But [the default directive_prefix is #PBS](https://github.com/adaptivecomputing/torque/blob/master/src/cmds/qsub_functions.c#L3709), so this should work. This breaks [gjbex/worker](https://github.com/gjbex/worker/blob/1.5.1/src/perl/Pbs/Description.pm#L16).

**Comment by stdweird** [comment]
inserted `sys.stderr.write("args %s" % (arguments))` before https://github.com/hpcugent/vsc-jobs/blob/master/bin/submitfilter.py#L126 gives
```
[vsc40002@node2159 ~]$ qsub -C '#PBS' -l nodes=1 s.sh
args ['/usr/bin/submitfilter', '-C']Traceback (most recent call last):
  File "/usr/bin/submitfilter", line 151, in <module>
```

looks like qsub passes the args to the submitfilter (via subshell?) as a joined string, not an array of args.

**Comment by stdweird** [comment]
as mentioned on chat, workarounds are
```bash
export PBS_DPREFIX='#PBS'
```
or 
```
-C '\#PBS`
```

**Comment by boegel** [comment]
@stdweird so, should this be fixed in the submitfilter, or in worker? or both?

**Comment by stdweird** [comment]
permanent fix in qsub (see ticket 5906 for followup), workaround in worker (https://github.com/gjbex/worker/pull/28), proper perl dependencies for worker in easyconfig (current module is not usable at all)

**Comment by boegel** [comment]
Thanks for the info @stdweird, see https://github.com/hpcugent/easybuild-easyconfigs/issues/2845 for the latter.

**Comment by gjbex** [comment]
Just out of curiosity, which version of qsub is this?

**Comment by stdweird** [comment]
@gjbex 5.1, but probably any version suffers from it

**Comment by ehiggs** [comment]
Is this fixed?

**Comment by gjbex** [comment]
@ehiggs If the question is whether qsub now works with -C, at least not in 6.0.1.  For worker, it was fixed in 1.6.5 (note: use 1.6.6, since the fix in 1.6.5 introduced a problem down the road).

**Comment by ehiggs** [comment]
@gjbex The question is whether I can close this. :) If there are workarounds in place that users don't need to worry about then I'm happy to close this.

**Comment by gjbex** [comment]
@ehiggs I guess this can be closed.
